provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-prevalence-predictor-spamm:
    lang: dockerfile
    handler: ./fn-prevalence-predictor-spamm
    image: disarm/fn-prevalence-predictor-spamm:0.1.0
    environment:
      exec_timeout: 600
      write_timeout: 700
      read_timeout: 700
      combine_output: false
      # write_debug: true
    labels:
      com.openfaas.scale.zero: true
