provider:
  name: openfaas
  gateway: https://faas.srv.disarm.io
functions:
  fn-prevalence-predictor-spamm:
    lang: r-geospatial
    handler: ./function
    image: disarm/fn-prevalence-predictor-spamm:0.2.0   
    environment:
      combine_output: false
      write_timeout: 600
      read_timeout: 600
      exec_timeout: 600
      write_debug: true
    labels:
      com.openfaas.scale.zero: true
