provider:
  name: openfaas
  gateway: https://faas.srv.disarm.io
functions:
  fn-prevalence-predictor-spamm:
    lang: r-geospatial
    handler: ./fn-prevalence-predictor-spamm
    image: disarm/fn-prevalence-predictor-spamm:0.1.0
    environment:
      combine_output: false
      # write_debug: true
    labels:
      com.openfaas.scale.zero: true
