provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-prevalence-predictor-spaMM:
    lang: dockerfile
    handler: ./fn-prevalence-predictor-spaMM
    image: disarm/fn-prevalence-predictor-spaMM:0.0.1
    environment:
      exec_timeout: 600
      write_timeout: 700
      read_timeout: 700
      combine_output: false
      # write_debug: true
